name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Gera uma nova cobra a cada dia à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Marcus-Vinicius-Dev
          outputs: dist/snake.svg
      - name: Push Snake
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
          directory: dist
